version: '3'
services:
  scope:
    image: weaveworks/scope:1.12.0
    container_name: scope
    hostname: scope
    network_mode: "host"
    pid: "host"
    privileged: true
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker=true"
    ports:
      - 4040:4040